# exposing river as a service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: river
    type: api
  name: river
  namespace: kube-system
spec:
  ports:
  - name: api
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: river
    type: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: river
    type: api
  name: river
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: river
      type: api
  template:
    metadata:
      labels:
        app: river
        type: api
      name: river
    spec:
      containers:
      - name: river
        image: ading1977/river:20170626
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: api
          protocol: TCP
