apiVersion: v1
kind: ReplicationController
metadata:
  name: firmament-ara
  namespace: sky-firmament
  labels:
    app: firmament-ara
    version: v0.3
spec:
  replicas: 1
  selector:
    app: firmament-ara
  template:
    metadata:
      labels:
        app: firmament-ara
        version: v0.3
    spec:
      containers:
      - name: firmament-ara
        image: registry.harbor:5000/sky-firmament/ara:20170626
        imagePullPolicy: Always
        env:
           - name: ETCD_URL
             valueFrom:
               configMapKeyRef:
                 name: config
                 key: etcd.url
           - name: HARBOR_URL
             valueFrom:
               configMapKeyRef:
                  name: config
                  key: harbor.host
           - name: reg_domain
             valueFrom:
               configMapKeyRef:
                  name: config
                  key: reg.domain
        resources:
          limits:
           # cpu: 200m
            memory: 400Mi
          requests:
            #cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 8080
