apiVersion: v1
kind: Service
metadata:
  name: ara-firmament-com
  namespace: sky-firmament
  labels:
    app: firmament-ara
spec:
  selector:
    app: firmament-ara
  ports:
  - port: 8082
    targetPort: 8080
  #sessionAffinity: ClientIP
