apiVersion: v1
kind: ReplicationController
metadata:
  name: firmament-lyra
  namespace: sky-firmament
  labels:
    app: firmament-lyra
    version: v0.3
spec:
  replicas: 1
  selector:
    app: firmament-lyra
  template:
    metadata:
      labels:
        app: firmament-lyra
        version: v0.3
    spec:
      containers:
      - name: firmament-lyra
        image: ading1977/lyra:20170626
        imagePullPolicy: Always
        env:
           - name: ETCD_URL
             valueFrom:
               configMapKeyRef:
                 name: config
                 key: etcd.url
           - name: KUBERNETES_URL
             valueFrom:
               configMapKeyRef:
                 name: config
                 key: kubernetes.url
        resources:
          limits:
            memory: 600Mi
          requests:
            memory: 600Mi
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: kubectl-path
            mountPath: /usr/bin/kubectl
      volumes:
        - name: kubectl-path
          hostPath:
            path: /usr/bin/kubectl
