apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: sky-firmament
  labels:
    app: elasticsearch-logging
spec:
  ports:
  - port: 9200
    protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: Endpoints
metadata:
  name: elasticsearch-logging
  namespace: sky-firmament
subsets:
  - addresses: 
    - ip: "172.16.10.4"
    ports:
    - port: 9200
      protocol: TCP

