apiVersion: v1
kind: Service
metadata:
  name: fornax-firmament-com
  namespace: sky-firmament
  labels:
    app: firmament-fornax
spec:
  selector:
    app: firmament-fornax
  ports:
  - port: 8085
    targetPort: 8080
    nodePort: 31085
  type: NodePort
